In [1]:
import pandas as pd

In [6]:
#Series
s = pd.Series([1,2,3,4,5])
print(s)

#index
print(s[2])

0    1
1    2
2    3
3    4
4    5
dtype: int64
3

In [14]:
#label
s = pd.Series([22,23,24,25] , index=["Adam","Bob","Charlie","Jack"])
print(s)
print(s["Adam"])
print(s.index)

Adam       22
Bob        23
Charlie    24
Jack       25
dtype: int64
22
Index(['Adam', 'Bob', 'Charlie', 'Jack'], dtype='str')

In [19]:
#vectorized
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,20,30,40,50])
print(s1 + s2)

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [23]:
#DataFrames
#with dictoniry of lists 
info = {
    "name":["Ram","Sparsh","Shubh"],
    "age":[19,23,21],
    "gpa":[7.0,8.3,7.8]
}

df = pd.DataFrame(info)
print(df)
print(df.index)
print(df.columns)

     name  age  gpa
0     Ram   19  7.0
1  Sparsh   23  8.3
2   Shubh   21  7.8
RangeIndex(start=0, stop=3, step=1)
Index(['name', 'age', 'gpa'], dtype='str')

In [25]:
# With lists of list
df = pd.DataFrame([["Adam",23],["Bob",24],["Eve",25]] , columns=["Name","Age"])
print(df)

   Name  Age
0  Adam   23
1   Bob   24
2   Eve   25

In [26]:
#With Numpy arrays
import numpy as np 

np_arr = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(np_arr , columns=["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [27]:
#Working with CSV Data
df = pd.read_csv("employee_data.csv")
print(df)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [37]:
#Different methods
df.head() # starting 5 rows
df.tail(2)
df.sample() #random value

df.info() #summary of the data
df.shape #tuple of (row,col)

df.describe() #statistical data about numbers

df.nunique() #unique rows

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     str
 2   Age         10 non-null     int64
 3   Department  10 non-null     str
 4   Salary      10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 628.0 bytes

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [42]:
#AQI Dataset

df = pd.read_csv("globalAirQuality.csv")
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [61]:
#Selecting Data
df["city"]
df[["city","aqi"]]
df.loc[0]
df.loc[0:2] #start:end , end is inclusive

df.iloc[0]
df.iloc[0:2] #start:end , end is not inclusive

#cells (row,col)
df.loc[101,"aqi"]
df.loc[0:3,["city","aqi"]]

df.columns
df.iloc[0:3 , [1,2]]

#selecting single scalar value
df.at[0,"city"]
df.iat[0,2]

'New York'

In [64]:
#Filtering Data
df[ df["aqi"] > 100]
df[ (df["aqi"] > 100) & (df["temperature"] > 30)]

df[ df["aqi"] > 100][["city","aqi"]] #chaining

           city  aqi
0      New York  108
3      New York  158
6      New York  155
7      New York  115
8      New York  121
...         ...  ...
17991    Zurich  104
17993    Zurich  153
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122

[9721 rows x 2 columns]